sudo: false

language: python

python:
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
env:
  - DJANGO_VERSION=1.11 DATABASE_URL=postgres://postgres@127.0.0.1/dbq
  - DJANGO_VERSION=2.2 DATABASE_URL=postgres://postgres@127.0.0.1/dbq
  - DJANGO_VERSION=1.11 DATABASE_URL=mysql://root@127.0.0.1/dbq
  - DJANGO_VERSION=2.2 DATABASE_URL=mysql://root@127.0.0.1/dbq

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.pyenv_cache

install:
  - pip install -r tests/requirements.txt

script: 
  - python manage.py test

# after_script:
#   - |
#       python igor.py combine_html
#       pip install codecov
#       codecov -X gcov --file coverage.xml