language: python
sudo: false
services:
  - mysql
  - postgresql
python:
- '3.6'
- '3.7'
- '3.8'
env:
- DJANGO_VERSION=2.2 DATABASE_URL=postgres://postgres@127.0.0.1/dbq_exports
- DJANGO_VERSION=2.2 DATABASE_URL=mysql://root@127.0.0.1/dbq_exports
install:
- pip install -r tests/requirements.txt
- pip install -U django==$DJANGO_VERSION
script:
  - python manage.py test