#!/bin/bash

set -e

run_pyenv() {
    if hash pyenv 2>/dev/null;
    then
        echo "using pyenv wrapper"
        pyenv install --skip-existing
        pyenv exec python -m venv env
    else
        echo "using 'python -m venv env'"
        python -m venv env
    fi
}


run_pip() {
    env/bin/pip install -r requirements.txt
}

run_pyenv
run_pip
