#!/bin/bash

set -e

rm -rf dist/

env/bin/pip install --upgrade setuptools wheel
env/bin/python setup.py sdist bdist_wheel

echo "Package built for distribution successfully..."

read -p "Do you wish to publish the package to the Python Package Index? (If no, the package will be published to the TEST PyPi) - or press ctrl+C to cancel " yn
env/bin/pip install twine
case $yn in
    [Yy]* ) env/bin/twine upload dist/*;;
    * ) env/bin/twine upload --repository-url https://test.pypi.org/legacy/ dist/*;;
esac
